//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RezaB.NetInvoice.Wrapper.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RezaB.NetInvoice.Wrapper.Errors.ErrorCodes", typeof(ErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 ERROR PARSING MOF RESPONSE.
        /// </summary>
        internal static string E0 {
            get {
                return ResourceManager.GetString("E0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 READY TO SEND.
        /// </summary>
        internal static string E1 {
            get {
                return ResourceManager.GetString("E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000 ENVELOPE ADDED IN QUEUE.
        /// </summary>
        internal static string E1000 {
            get {
                return ResourceManager.GetString("E1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1100 PROCESSING THE ENVELOPE.
        /// </summary>
        internal static string E1100 {
            get {
                return ResourceManager.GetString("E1100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1110 NOT A ZIP FILE.
        /// </summary>
        internal static string E1110 {
            get {
                return ResourceManager.GetString("E1110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1111 INVALID ENVELOPE ID LENGTH.
        /// </summary>
        internal static string E1111 {
            get {
                return ResourceManager.GetString("E1111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1120 ENVELOPE COULD NOT BE EXTRACTED FROM ARCHIVE.
        /// </summary>
        internal static string E1120 {
            get {
                return ResourceManager.GetString("E1120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1130 ZIP EXTRACTION ERROR.
        /// </summary>
        internal static string E1130 {
            get {
                return ResourceManager.GetString("E1130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1131 ZIP SHOULD CONTAIN A FILE.
        /// </summary>
        internal static string E1131 {
            get {
                return ResourceManager.GetString("E1131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1132 NOT A XML FILE.
        /// </summary>
        internal static string E1132 {
            get {
                return ResourceManager.GetString("E1132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1133 ENVELOPE ID AND XML FILE MUST HAVE THE SAME NAME.
        /// </summary>
        internal static string E1133 {
            get {
                return ResourceManager.GetString("E1133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1140 DOCUMENT COULD NOT BE SEPARATED.
        /// </summary>
        internal static string E1140 {
            get {
                return ResourceManager.GetString("E1140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1141 ENVELOPE ID MISSING.
        /// </summary>
        internal static string E1141 {
            get {
                return ResourceManager.GetString("E1141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1142 ENVELOPE ID AND ZIP FILE MUST HAVE SAME NAME.
        /// </summary>
        internal static string E1142 {
            get {
                return ResourceManager.GetString("E1142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1143 INVALID VERSION.
        /// </summary>
        internal static string E1143 {
            get {
                return ResourceManager.GetString("E1143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1150 SCHEMATRON CONTROL RESULT ERROR.
        /// </summary>
        internal static string E1150 {
            get {
                return ResourceManager.GetString("E1150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1160 SCHEME VALIDATION ERROR.
        /// </summary>
        internal static string E1160 {
            get {
                return ResourceManager.GetString("E1160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1161 CITIZENSHIP NUMBER OR TAX ID OF SIGNATORY COULD NOT BE RECEIVED.
        /// </summary>
        internal static string E1161 {
            get {
                return ResourceManager.GetString("E1161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1162 SIGNATURE COULD NOT BE RECORDED.
        /// </summary>
        internal static string E1162 {
            get {
                return ResourceManager.GetString("E1162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1163 ENVELOPE CONTAINS AN INVOICE ALREADY RECORDED.
        /// </summary>
        internal static string E1163 {
            get {
                return ResourceManager.GetString("E1163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1170 AUTHORIZATION COULD NOT BE CHECKED.
        /// </summary>
        internal static string E1170 {
            get {
                return ResourceManager.GetString("E1170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1171 SENDER IS NOT AUTHORIZED.
        /// </summary>
        internal static string E1171 {
            get {
                return ResourceManager.GetString("E1171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1172 NO ACCESS TO MAIL BOX.
        /// </summary>
        internal static string E1172 {
            get {
                return ResourceManager.GetString("E1172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1175 AUTHORIZATION TO SIGN COULD NOT BE CHECKED.
        /// </summary>
        internal static string E1175 {
            get {
                return ResourceManager.GetString("E1175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1176 UNAUTHORIZED SIGNATURE.
        /// </summary>
        internal static string E1176 {
            get {
                return ResourceManager.GetString("E1176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1180 ADDRESS COULD NOT BE CHECKED.
        /// </summary>
        internal static string E1180 {
            get {
                return ResourceManager.GetString("E1180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1181 ADDRESS NOT FOUND.
        /// </summary>
        internal static string E1181 {
            get {
                return ResourceManager.GetString("E1181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1190 SYSTEM RESPONSE NOT PRODUCED.
        /// </summary>
        internal static string E1190 {
            get {
                return ResourceManager.GetString("E1190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1195 SYSTEM ERROR.
        /// </summary>
        internal static string E1195 {
            get {
                return ResourceManager.GetString("E1195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 MAPPING ERROR.
        /// </summary>
        internal static string E12 {
            get {
                return ResourceManager.GetString("E12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1200 ENVELOPE RECEIVED SUCCESFULLY.
        /// </summary>
        internal static string E1200 {
            get {
                return ResourceManager.GetString("E1200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1210 DOCUMENT COULD NOT BE SENT TO ADDRESS.
        /// </summary>
        internal static string E1210 {
            get {
                return ResourceManager.GetString("E1210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1215 DOCUMENT SENDING FAILURE. RESENDING COMPLETED..
        /// </summary>
        internal static string E1215 {
            get {
                return ResourceManager.GetString("E1215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1220 SYSTEM RESPONSE NOT RECEIVED FROM TARGET.
        /// </summary>
        internal static string E1220 {
            get {
                return ResourceManager.GetString("E1220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1230 UNSUCCESFUL SYSTEM RESPONSE FROM TARGET.
        /// </summary>
        internal static string E1230 {
            get {
                return ResourceManager.GetString("E1230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13 MAPPING SUCCESS.
        /// </summary>
        internal static string E13 {
            get {
                return ResourceManager.GetString("E13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1300 COMPLETED SUCCESFULLY.
        /// </summary>
        internal static string E1300 {
            get {
                return ResourceManager.GetString("E1300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14 UBL CONVERSION ERROR.
        /// </summary>
        internal static string E14 {
            get {
                return ResourceManager.GetString("E14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 UBL CONVERSION SUCCESS.
        /// </summary>
        internal static string E15 {
            get {
                return ResourceManager.GetString("E15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16 XML VALIDATION ERROR.
        /// </summary>
        internal static string E16 {
            get {
                return ResourceManager.GetString("E16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17 XML VALIDATION SUCCESS.
        /// </summary>
        internal static string E17 {
            get {
                return ResourceManager.GetString("E17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18 SIGN ERROR.
        /// </summary>
        internal static string E18 {
            get {
                return ResourceManager.GetString("E18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19 SIGN SUCCESS.
        /// </summary>
        internal static string E19 {
            get {
                return ResourceManager.GetString("E19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 RULE VALIDATION ERROR.
        /// </summary>
        internal static string E20 {
            get {
                return ResourceManager.GetString("E20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000 SUMMARIZED VALUES ARE NOT EQUAL.
        /// </summary>
        internal static string E2000 {
            get {
                return ResourceManager.GetString("E2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2001 ENVELOPE ID ALREADY EXISTS.
        /// </summary>
        internal static string E2001 {
            get {
                return ResourceManager.GetString("E2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2002 ENVELOPE ARCHIVING ERROR.
        /// </summary>
        internal static string E2002 {
            get {
                return ResourceManager.GetString("E2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2003 ENVELOPE COULD NOT BE ADDED IN QUEUE.
        /// </summary>
        internal static string E2003 {
            get {
                return ResourceManager.GetString("E2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2004 ENVELOPE ID NOT FOUND.
        /// </summary>
        internal static string E2004 {
            get {
                return ResourceManager.GetString("E2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2005 SYSTEM ERROR.
        /// </summary>
        internal static string E2005 {
            get {
                return ResourceManager.GetString("E2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2006 INVALID ENVELOPE NAME.
        /// </summary>
        internal static string E2006 {
            get {
                return ResourceManager.GetString("E2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21 RULE VALIDATION SUCCESS.
        /// </summary>
        internal static string E21 {
            get {
                return ResourceManager.GetString("E21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22 ARCHIVING ERROR.
        /// </summary>
        internal static string E22 {
            get {
                return ResourceManager.GetString("E22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23 ARCHIVING SUCCESS.
        /// </summary>
        internal static string E23 {
            get {
                return ResourceManager.GetString("E23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 REGISTERED IN SYSTEM.
        /// </summary>
        internal static string E24 {
            get {
                return ResourceManager.GetString("E24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25 WAITING FOR APPROVAL.
        /// </summary>
        internal static string E25 {
            get {
                return ResourceManager.GetString("E25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26 SENDING ERROR.
        /// </summary>
        internal static string E26 {
            get {
                return ResourceManager.GetString("E26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27 ENVELOPE SCHEMA SUCCESS.
        /// </summary>
        internal static string E27 {
            get {
                return ResourceManager.GetString("E27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28 ENVELOPE SCHEMA ERROR.
        /// </summary>
        internal static string E28 {
            get {
                return ResourceManager.GetString("E28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29 INVOICE ALREADY EXISTS.
        /// </summary>
        internal static string E29 {
            get {
                return ResourceManager.GetString("E29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 AT LEAST ONE ERRONEOUS INVOICE IN ENVELOPE.
        /// </summary>
        internal static string E30 {
            get {
                return ResourceManager.GetString("E30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31 ENVELOPE CANNOTINCLUDE MULTIPLE RECEIVERTAXID OR SENDERTAXID.
        /// </summary>
        internal static string E31 {
            get {
                return ResourceManager.GetString("E31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32 ARCHIVED.
        /// </summary>
        internal static string E32 {
            get {
                return ResourceManager.GetString("E32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33 SENT.
        /// </summary>
        internal static string E33 {
            get {
                return ResourceManager.GetString("E33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 34 SYSTEM ERROR.
        /// </summary>
        internal static string E34 {
            get {
                return ResourceManager.GetString("E34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35 WAITING FOR RECONCILIATION.
        /// </summary>
        internal static string E35 {
            get {
                return ResourceManager.GetString("E35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 36 RECONCILIATION SENT.
        /// </summary>
        internal static string E36 {
            get {
                return ResourceManager.GetString("E36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 37 WAITING FOR SIGN.
        /// </summary>
        internal static string E37 {
            get {
                return ResourceManager.GetString("E37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38 SCHEMATRON VALIDATION ERROR.
        /// </summary>
        internal static string E38 {
            get {
                return ResourceManager.GetString("E38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 39 SCHEMATRON VALIDATION SUCCESS.
        /// </summary>
        internal static string E39 {
            get {
                return ResourceManager.GetString("E39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 INVALID XML.
        /// </summary>
        internal static string E40 {
            get {
                return ResourceManager.GetString("E40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41 WAITING FOR SEND APPROVAL.
        /// </summary>
        internal static string E41 {
            get {
                return ResourceManager.GetString("E41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42 REJECTED.
        /// </summary>
        internal static string E42 {
            get {
                return ResourceManager.GetString("E42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 43 WAITING FOR CLIENT SIGNATURE.
        /// </summary>
        internal static string E43 {
            get {
                return ResourceManager.GetString("E43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 44 SIGN VERIFICATION ERROR.
        /// </summary>
        internal static string E44 {
            get {
                return ResourceManager.GetString("E44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9100 WAITING FOR APPROVAL RESULT.
        /// </summary>
        internal static string E9100 {
            get {
                return ResourceManager.GetString("E9100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9101 APPROVED.
        /// </summary>
        internal static string E9101 {
            get {
                return ResourceManager.GetString("E9101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9103 WAITING FOR MOF UPDATING RESULT.
        /// </summary>
        internal static string E9103 {
            get {
                return ResourceManager.GetString("E9103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99 DOCUMENT RECEIVED BY GIB.
        /// </summary>
        internal static string E99 {
            get {
                return ResourceManager.GetString("E99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9987 INVOICE ACCEPTED.
        /// </summary>
        internal static string E9987 {
            get {
                return ResourceManager.GetString("E9987", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9988 INVOIVE REJECTED.
        /// </summary>
        internal static string E9988 {
            get {
                return ResourceManager.GetString("E9988", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 999 ACCESS DENIED.
        /// </summary>
        internal static string E999 {
            get {
                return ResourceManager.GetString("E999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9999 CONNECTION ERROR.
        /// </summary>
        internal static string E9999 {
            get {
                return ResourceManager.GetString("E9999", resourceCulture);
            }
        }
    }
}
